version: '3.3'

services:
  nginx:
    image: nginx:1.12.1
    container_name: nginx
    dns: 8.8.8.8
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./root_project:/var/www/html
      - ./config/nginx/sites-enabled/vhost-magento.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php
  php:
    container_name: php
    image: meanbee/magento:${PHP_VERSION}
    restart: always
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./root_project:/var/www/html
      - tn-volume-sync:/var/www/html:nocopy
      - ./config/php/extension:/usr/local/etc/php/conf.d
      - ~/.ssh:/var/www/.ssh-local:ro
      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
    expose:
      - 9000
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "8989:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    networks:
      - back

networks:
  back:
    driver: bridge

volumes:
  tn-volume-sync:
    external: true